### ISSUE TITLE
[DOCKER] Not showing API token

### ISSUE THREAD

**Issue by Dielee** [ReceiptManager/receipt-parser-server#25]
I am planning to build a javascript webinterface on the receipt server. 
Unfortunately the docker container does not show any api token. 
Postman reports:
```
{
    "detail": "Could not validate credentials"
}
```

EDIT: I scanned the QR Code, but it seems to be empty...

**Comment by monolidth** [comment]
Sorry for the late response, I don't receive any notification and thanks for catching.

If I build the docker image locally it seems to work.

**Comment by monolidth** [comment]
I found the bug. It does work (for me) if I attack Docker to a pseudo TTY. Please run the image with the -t -i flag. You can read more about [here](https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html#process-behavior-inside-docker-containers).


## Steps
```
docker pull monolidth/receipt-parser:latest
docker run -i -t monolidth/receipt-parser
```

I will fix the documentation today. If you want to talk more about your webinterface project, we could do this via Zoom.

Regards,

William

**Comment by Dielee** [comment]
First, thanks for your answer. 
Now the qr code is displayed to me. But Google lense can not read the qr code, or the code is empty.

Any Ideas ?

**Comment by Dielee** [comment]
Displayed QR code:
![2021-03-18 10_23_18-Window](https://user-images.githubusercontent.com/45101649/111602843-0dd7e000-87d4-11eb-9942-9d5347d9fff2.png)

**Comment by monolidth** [comment]
Yes, your right.

**Comment by monolidth** [comment]
Please try the latest commit: https://github.com/ReceiptManager/receipt-parser-server/commit/54a54326b25838dd35dbce0559ff23e691f1d30b

**Comment by Dielee** [comment]
Yes, this works! Thank you!

I am now passing in the header my access_token, that seems to work well. 
But now Postman gives me the following error message:

``` json {
    "detail": [
        {
            "loc": [
                "body",
                "file"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        }
    ]
}

**Comment by monolidth** [comment]
Are you using the client or what are your trying to do? Looks like you miss to set the image e.g. using the multipart/form-data.

```
curl -X POST "https://[ip]:8721/api/upload?access_token=[token]&legacy_parser=False&grayscale_image=True" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -F "file=@image.jpeg;type=image/jpeg" -k
```

**Comment by Dielee** [comment]
Thank you for this sample cURL command. 
How to disable https for docker container ? 

EDIT: I edited config.yaml inside the docker container

**Comment by Dielee** [comment]
Soo, I have made progress with my polymer frontend. I'm now able to upload an image and send it to the parser.
Now I'm getting an CORS error. This seems to be an backend error.
Do you have an idea ? 
![2021-03-18 15_34_34-Receipt Parser Web](https://user-images.githubusercontent.com/45101649/111643958-aafc3e00-87ff-11eb-97cd-cb0d37d9e6a9.png)

**Comment by monolidth** [comment]
The easiest way to disable HTTPS is to edit the config file.

## Steps
### 1. Set https to false inside the `config.yml`
### 2. Rebuild the Docker image
```
make docker-build
make docker-run
```

**Comment by monolidth** [comment]
According to stackoverflow:
> I believe this might likely be that Chrome does not support localhost to go through the Access-Control-Allow-Origin

See: https://stackoverflow.com/questions/28547288/no-access-control-allow-origin-header-is-present-on-the-requested-resource-err

**Comment by monolidth** [comment]
Maybe, I will add CORS Middleware:
https://fastapi.tiangolo.com/tutorial/cors/

**Comment by Dielee** [comment]
This would be very nice! 

My progress so far from today:

![2021-03-18 17_00_49-Receipt Parser Web](https://user-images.githubusercontent.com/45101649/111657226-86a65e80-880b-11eb-8f79-a63b978e5ad9.png)

**Comment by monolidth** [comment]
Looks great but where is the receipt stored?

**Comment by Dielee** [comment]
I have made some more progress today and build an own python backend to solve the CORS problem. 
Unfortunately, the ocr of the receipts is really bad. 
Is there any way to improve it ? 
Here is an example:

![IMG_20210319_143322](https://user-images.githubusercontent.com/45101649/111791806-e06a5f80-88c3-11eb-8f88-22cb8a012f8d.jpg)

OCR Result:

[IMG_20210319_143322.txt](https://github.com/ReceiptManager/receipt-parser-server/files/6171602/IMG_20210319_143322.txt)

This worked WAY! better in previous versions...
I'm using this call:
`http://192.168.50.59:5558/api/upload?access_token=nq8jwDvUCAUxQ&legacy_parser=True&grayscale_image=True&rotate_image=True`

**Comment by monolidth** [comment]
I try your image with following parameters
* gaussian blur=True
* median blur=True
* grayscale=True

and I get pretty good results.

See:
![image](https://user-images.githubusercontent.com/71930307/111816060-abb6d200-88dc-11eb-8698-6478a353808f.png)

I did not touch the receipt-parser, maybe try to apply blur and share results.

Regards,
William

**Comment by Dielee** [comment]
YES! Works really good!

![Screenshot_20210319-184816](https://user-images.githubusercontent.com/45101649/111822265-e2dcb180-88e3-11eb-9152-a35f5a4a052c.jpg)

**Comment by Dielee** [comment]
Thanks for your help !

**Comment by monolidth** [comment]
you’re welcome!

**Comment by Dielee** [comment]
Sorry, but here I am again..
Some photos are very good, others don't work at all.. sample:

![Screenshot_20210320-131522](https://user-images.githubusercontent.com/45101649/111869180-5b904c00-897e-11eb-94ee-687d7afaa8c1.jpg)
![IMG_20210320_130553](https://user-images.githubusercontent.com/45101649/111869193-6ba82b80-897e-11eb-8545-485c37ea63ea.jpg)

**Comment by Dielee** [comment]
I tried a bit more and found something strange.
This photo: 
![IMG_20210320_1428102](https://user-images.githubusercontent.com/45101649/111872094-df9e0000-898d-11eb-9f5e-4a9908562d72.jpg)

is parsed really well, but receiptItems JSON response is empty! 
OCR TXT:
[IMG_20210320_1428102.txt](https://github.com/ReceiptManager/receipt-parser-server/files/6175739/IMG_20210320_1428102.txt)

Maybe its possible to talk via Zoom or something else within the next days ?

**Comment by monolidth** [comment]
Confirmed, this is really strange even the regex match:
![image](https://user-images.githubusercontent.com/71930307/111877368-585b8700-89a3-11eb-9ffa-de8e5f0be514.png)

Sure, maybe next Wednesday?

Regards,

William

**Comment by Dielee** [comment]
Yes, I checked this, too. 
Maybe I will dig into this tomorrow.
Wednesday should be fine for me!

**Comment by Dielee** [comment]
I found the issue!
Stop word "Pfand" was triggered...

**Comment by monolidth** [comment]
Yes, your right! Thanks for catching.

## Output
![image](https://user-images.githubusercontent.com/71930307/112036990-8c6cae80-8b41-11eb-96e0-404a5ba1e112.png)


Looks pretty promising. 

Regards,

William

**Comment by monolidth** [comment]
Fixed in https://github.com/ReceiptManager/receipt-parser-legacy/commit/5efb65bde73ec16c0e72342bbf7a387d837a6c29

**Comment by Dielee** [comment]
Thanks for fixing! 
I'm trying to improve ocr quality tomorrow with using --psm, as the item order seems to be mixed some time.

**Comment by monolidth** [comment]
Well, `--psm 6` gives (for me) the best results. When do you have time on Wednesday?

Regards,
William

**Comment by Dielee** [comment]
Yes, that's right. Using --psm 6 gave me the best results, too.
Would be nice if you would merge this change. But I can submit an PR also. 
The change would be in line 136 enhancer.py from legacy parser.

` image_data = pytesseract.image_to_string(img, lang=language, timeout=60, config="--psm 6")`


Tomorrow we can talk at launch break. Maybe 13 o'clock ?

**Comment by monolidth** [comment]
Merged in https://github.com/ReceiptManager/receipt-parser-legacy/commit/fdf983c7cdd2ee1ef01c23f8f67685d0dbb32524

13 o'clock does not work for me. I have time after 4pm. You can send me your email address to provide the zoom link.

**Comment by Dielee** [comment]
Thanks for merging! 
Is it possible to release a new pipy version ? 
I want so install those changes on my parsing container. 

4 o'clock is fine for me!

**Comment by Dielee** [comment]
I dug deeper again and found why the ocr sometimes takes so long.
The receipts are processed twice with WandImage. 
This results in a high CPU load and long processing time.

The receipt is processed in `sharpen_image` and in `run_tesseract`
with wand image. 

`run_tesseract` should look like this:

```
def run_tesseract(input_file, output_file, language="deu"):
    """
    :param input_file: str
        Path to image to OCR
    :param output_file: str
        Path to output file
    :return: void
        Runs tesseract on image and saves result
    """

    print(ORANGE + '\t~: ' + RESET + 'Parse image using pytesseract' + RESET)
    print(ORANGE + '\t~: ' + RESET + 'Parse image at: ' + input_file + RESET)
    print(ORANGE + '\t~: ' + RESET + 'Write result to: ' + output_file + RESET)

    with io.BytesIO() as transfer:
        with WandImage(filename=input_file) as img:
            img.save(transfer)

        with Image.open(transfer) as img:
            image_data = pytesseract.image_to_string(img, lang=language, timeout=60, config="--psm 6")

            out = open(output_file, "w")
            out.write(image_data)
            out.close()
```

Before adjustment, the receipts sometimes took > 20 seconds. 
After the adjustment we stay at least under 5!
The ocr result is the same.

**Comment by monolidth** [comment]
Yeah, looks like it is executed twice. I fix this now and publish the build on `pipy`. Thanks for catching!

Regards,
William

**Comment by monolidth** [comment]
See: https://github.com/ReceiptManager/receipt-parser-legacy/commit/1505c7f268814b076e39ece6311f2aa5db593278

**Comment by Dielee** [comment]
Thank you very much! This works very nice!

![Screenshot_20210323-111959](https://user-images.githubusercontent.com/45101649/112131417-d4371880-8bc9-11eb-9935-8c5edf790cc4.jpg)

**Comment by Dielee** [comment]
One more thing! 
Would you please change inside the dateparsing function this line:
`match = re.match(self.config.date_format, line)`

to 
`match = re.search(self.config.date_format, line)`

Date parsing works fine after this change.

**Comment by monolidth** [comment]
Looks really promising! 

> match = re.search(self.config.date_format, line)

I disagree with that since this would match also 9814.05 e.g.
I think sometimes it is better to return None because the user is aware of an empty value (instead of wrong one).

Regards,
William

**Comment by monolidth** [comment]
![image](https://user-images.githubusercontent.com/71930307/112139408-0436e980-8bd3-11eb-97a2-31fe6999140e.png)

**Comment by Dielee** [comment]
Change your regex to (\d{1,2}\.\d{1,2}\.\d{2,4}) :)

**Comment by monolidth** [comment]
Does not work for me for now but at the moment I don't have time to debug. Sorry :(

**Comment by Dielee** [comment]
That's strange... Works fine for me..



![2021-03-23 13_34_07-config yml - receipt_parser_core  WSL_ Ubuntu-20 04  - Visual Studio Code](https://user-images.githubusercontent.com/45101649/112146983-795aec80-8bdc-11eb-85d0-d5f1fc584caa.png)

EDIT: Tried with your IMG004 Sample and got the same error.

Try this regex: (\d{2}\.\d{2}\.\d{2,4})

**Comment by monolidth** [comment]
I would be more than happy if you could submit your changes via PR and should move this conversation to [gitter](https://gitter.im/receipt-parser-manager/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link) or mail :)

Regards,
William
