### ISSUE TITLE
zeroconf should be optional

### ISSUE THREAD

**Issue by LecrisUT** [ReceiptManager/receipt-parser-server#27]
There is a high potential that there are port conflicts when using zeroconf and I don't see a way to change the port used. So it would be better to have it optional. Also what if another service uses zeroconf? Can it detect it and not conflict?

**Comment by monolidth** [comment]
1. You could now set the zeroconf parameter if needed, to enable zeroconf https://github.com/ReceiptManager/receipt-parser-server/commit/a93a42b509f930cfac03f37db224dd0d17c73b0b

2. and I added a convenient way to push a new configuration (take a look at the `util/launcher.sh`).

Regards,

William
