### ISSUE TITLE
Server running on https://0.0.0.0:8721

### ISSUE THREAD

**Issue by maxx-st** [ReceiptManager/receipt-parser-server#28]
So i got it running (on a RPi), but it states, that the server is running on https://0.0.0.0:8721 and I can't connect to it.
Furthermore, the SSL-Handshake failed, even tho I follow the instruction correctly.
Any suggestions on how to get it running?

Thank you.

**Comment by monolidth** [comment]
Well `0.0.0.0` does mean any IPv4 address (because `Docker` uses its own subnet).

You can find your IP address using: `ip -br a`. The output looks the following:
```
enp3s0f0         DOWN
wlp1s0           UP             192.168.0.243/24 [IPv6 Address]
```

Which means that `192.168.0.243` is your current IP address.


The SSL certificate is a [self signed certificate](https://en.wikipedia.org/wiki/Self-signed_certificate) which appears to be untrusted. Are you using the client?

**Comment by kalismeras61** [comment]
I have same issue. Can't connect docker on macos even i tried local ip address. @monolidth  can you guide some thing ? 

I am using docker macOs app and i run image on docker. 
![Screen Shot 2021-05-13 at 16 06 18](https://user-images.githubusercontent.com/246747/118129747-3d3a5000-b405-11eb-8266-e3c380a13d32.png)

**Comment by kalismeras61** [comment]
on client application i am getting below error. 

Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by monolidth** [comment]
Hi @kalismeras61,
do you forward your IP like: `-i -t -p [YOUR-IP]:8721:8721`? Please disable HTTPS  at the moment or import the server certificate. You can disable HTTPS in the configuration file.

If there are any issues, please let me know :)

**Comment by kalismeras61** [comment]
Hi @monolidth ,

31256c78bc1b   monolidth/receipt-parser           "make serve"             21 hours ago   Up 8 minutes                192.168.68.110:8721->8721/tcp   suspicious_khorana
 

It looks i forward ip . When i run docker ps -a i am seeing this. By the way i am new on Docker and can't find config file. :(

**Comment by kalismeras61** [comment]
Hi @monolidth ,

31256c78bc1b   monolidth/receipt-parser           "make serve"             21 hours ago   Up 8 minutes                192.168.68.110:8721->8721/tcp   suspicious_khorana
 

It looks i forward ip . When i run docker ps -a i am seeing this. By the way i am new on Docker and can't find config file. :(

**Comment by monolidth** [comment]
Looks like you forward the IP. Have you tried the recommended installation guide?

You can find the installation guide [here](https://receipt-parser-server.readthedocs.io/en/master/installation.html).

Please download the default configuration file:
```
wget https://raw.githubusercontent.com/ReceiptManager/receipt-parser-server/master/util/launcher.sh
wget https://raw.githubusercontent.com/ReceiptManager/receipt-parser-server/master/config.yml
bash launcher.sh
```

The `launcher.sh` take care of all.

**Comment by monolidth** [comment]
If you the issue still persist, please let me know.

**Comment by kalismeras61** [comment]
@monolidth i am able to run the server. But can't find information for the default tesseract language ? How can i use different language ? Is there any documentation for it ?

As i understand we need to install tesseract as well right ?

**Comment by monolidth** [comment]
I took a look at the source and it looks like that this is not implemented. I will submit a fix shortly

**Comment by monolidth** [comment]
Will take roughly a hour

**Comment by monolidth** [comment]
Nevermind, it is implemented (I was confused by the default parameter). You can adjust the language in the configuration file.

**Comment by monolidth** [comment]
The idea is that  you replace the market names with your market names. You can find a tutorial at the readthedocs wiki

**Comment by monolidth** [comment]
Sorry, for the confusion

**Comment by kalismeras61** [comment]
@monolidth  no problem. Everythings looks fine as of now. Is the training endpoints works? As i see results not good for Turkish receipts, i need to try training things.

**Comment by monolidth** [comment]
I see, is the tesseract output also bad? The training was intended for the neuronal-network-parser and I currently do not support the legacy parser.

**Comment by monolidth** [comment]
Do you need help?

**Comment by kalismeras61** [comment]
@monolidth sorry for the late response. Tesseract results also bad it is selection automatically Aldi. Do you have any idea ?

**Comment by monolidth** [comment]
Well, do the following. The example configuration looks like this:
```yaml
    # Define the tesseract language
language: deu

# Enable https
https: true

# Where the receipts are stored
# Receipts should be simple text files
receipts_path: "data/txt"

# Market names roughly ordered by likelihood.
# Can contain market locations for fuzzy parsing
markets:
  Colruyt:
     - colruyt
     - Colruyt
  Delhaize:
     - Delhaize
     - delhaize
  Penny:
     - penny
     - p e n n y
     - m a r k t gmbh
    ...
```

Remove all market tags (includig aldi). The receipt parser library uses a fuzzy parser to determine the shop name.Therefore, you have to add your shop names (including likely names to improve the result).

For more information please check out the example [here](https://receipt-parser-server.readthedocs.io/en/master/config.html#example-config).

I'm not familiar with the turkish language but you can share the tesseract output located in `data/txt` so that I can help you.

Are you using the android client or do you use the scanner?

**Comment by kalismeras61** [comment]
@monolidth  ok will do that. I am using android client which you created with Flutter. ( Btw, you have to add debug parameters in build.gradle client app)

**Comment by kalismeras61** [comment]
@monolidth here is the some result. 

[8050f041-fb6b-4f70-8565-a40fb1a799073941569200040570013.txt](https://github.com/ReceiptManager/receipt-parser-server/files/6489150/8050f041-fb6b-4f70-8565-a40fb1a799073941569200040570013.txt)

Here is the taken image
![8ea98f7a-00e4-46cc-b39a-04cf9fcd51775437470644800334787](https://user-images.githubusercontent.com/246747/118396105-91883e80-b656-11eb-9830-cea639088215.jpg)

**Comment by monolidth** [comment]
Well, is not great, I agree. I spend some time in debugging. The first thing I noticed, is that the date regex does not match the date in your receipt.

![image](https://user-images.githubusercontent.com/71930307/118398136-88e43800-b657-11eb-9bbd-22c6b4233139.png)


**Solution:**
Replace the date regex in your config, with:
```
(0?[1-9]|[12][0-9]|3[01])-(0?[1-9]|1[012])-((?:19|20)[0-9][0-9])
```

![image](https://user-images.githubusercontent.com/71930307/118398087-67834c00-b657-11eb-9029-48af8e64938a.png)


The next problem is that the market is not in the list.

**Solution:**
Try to add the market like:
``` yaml
markets:
 EKMEKÇİ: 
  - EKMEKÇİ
```

Lastly, you need to define the turkish sum key in `sum_keys`. The parser scans for this sum key in your receipt and try to extract the total.

```yaml
sum_keys:
  - summe
    - gesamtbetrag
    - top // guess this means sum
```

If you need also the items on the receipt, please let me know.

**Comment by monolidth** [comment]
If, you want to help me out, you can improve the android app. You don't have to, but this would be quit helpful :)

**Comment by kalismeras61** [comment]
Yeah, i can help you with Client app

**Comment by kalismeras61** [comment]
@monolidth i already added market as you mention. For date format i changed the regex. It looks like it is matching in regex https://regexr.com/ but server doesn't found date. 


`date_format: '(0?[1-9]|[12][0-9]|3[01])-(0?[1-9]|1[012])-((?:19|20)[0-9][0-9])' `

Results from server: 

```
Company:     
Date:        12
Amount:      
Items:     
	* unlu mamülleri̇ /01   45.00
```

**Comment by monolidth** [comment]
Hey, I will debug this after I'm back at home. Maybe we move this conversation to the receipt-parser-legacy repository.

**Comment by monolidth** [comment]
The receipt was quite challenging. I'm able to extract all information (except items but I don't take a look at these).

![image](https://user-images.githubusercontent.com/71930307/118408539-4f76f100-b686-11eb-8292-a972d8ae95fe.png)

Was quite some work but I push to the `tur` branch.

**Comment by kalismeras61** [comment]
Cool thanks.

**Comment by kalismeras61** [comment]
@monolidth i am planning to create saas project but not sure it will works well for Turkish. Is the legacy one training works well ? I think i have to train bunch of receipts for each popular markets.

**Comment by monolidth** [comment]
Maybe, there is a missunderstanding. You can not train the legacy parser but you can train tesseract but I don't know if this is suitable for your purpose. A while ago I started to work on a neuronal network parser. This is the reason why I have this training endpoint. Thus, I used a too clean dataset and it worked on my receipts not so good.If you want I can share the source.

**Comment by kalismeras61** [comment]
@monolidth can you share source ?

**Comment by monolidth** [comment]
Sure, should I send this via E-Mail?

**Comment by kalismeras61** [comment]
Would be great
