### ISSUE TITLE
Cannot install server

### ISSUE THREAD

**Issue by GregTroar** [ReceiptManager/receipt-parser-server#29]
Hi,

Could not succeed with docker nor normal install:

Traceback (most recent call last):

  File "src/receipt_server.py", line 233, in <module>

    ssl_certfile=util.get_work_dir() + CERT_LOCATION, ssl_keyfile=util.get_work_dir() + KEY_LOCATION)

  File "/usr/local/lib/python3.6/dist-packages/uvicorn/main.py", line 386, in run

    server.run()

  File "/usr/local/lib/python3.6/dist-packages/uvicorn/server.py", line 48, in run

    loop.run_until_complete(self.serve(sockets=sockets))

  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete

    return future.result()

  File "/usr/local/lib/python3.6/dist-packages/uvicorn/server.py", line 55, in serve

    config.load()

  File "/usr/local/lib/python3.6/dist-packages/uvicorn/config.py", line 280, in load

    ciphers=self.ssl_ciphers,

  File "/usr/local/lib/python3.6/dist-packages/uvicorn/config.py", line 109, in create_ssl_context

    ctx.load_cert_chain(certfile, keyfile, get_password)

FileNotFoundError: [Errno 2] No such file or directory

Makefile:10: recipe for target 'serve' failed

make: *** [serve] Error 1

**Comment by monolidth** [comment]
Thanks for catching. I accidentally deleted the generate_cert method, which I don't even noticed since the certificate was already generated.

Solution: `make generate_cert`

Regards,
William

**Comment by GregTroar** [comment]
Thanks

**Comment by GregTroar** [comment]
Btw nowhere is mentioned to run a pip install -r requirements in the installation docs.

**Comment by monolidth** [comment]
I push the new Docker file shortly and fix the documentation. Thank you @rouggy :)

**Comment by monolidth** [comment]
I keep this issue open until it is completely fixed.

**Comment by monolidth** [comment]
Both should be resolved in:
* 7081d73a8da1f99906d183205c26641540301be5
* b667070691d240a52b8cc652be42aac2cc5b9b66

**Comment by LecrisUT** [comment]
Just a QOL comment, but try to use commit messages to close and link to commits/PRs like:
```
[DOCU] correct developer installation guide 
closes #29
```
Your favourite IDE, Github client or other git clients can help you with finding the appropriate link and writing the commit messages.

**Comment by monolidth** [comment]
Thanks, I try to improve my commit messages in the future.
