### ISSUE TITLE
Error on bash launcher.sh: API token is not valid or present, Generation is required

### ISSUE THREAD

**Issue by JavaJeremy** [ReceiptManager/receipt-parser-server#30]
I think there must be a step missing in the installation description to prevent this error from happening:

```
<user>@<server>:~# bash launcher.sh
Current IP is: <ip>
bash util/generate_certificate.sh
Submit default password
Generating RSA private key, 4096 bit long modulus (2 primes)
...........................................++++
............++++
e is <number> (0x010001)
Generating a RSA private key
...........................................................................................................+                       +++
.........................++++
writing new private key to 'cert/server.key'
-----
Signature ok
subject=C = DE, ST = Saxony, L = Leipzig, O = ReceiptParser, OU = ReceiptParser development team, emailAddre                       ss = development@receiptparser.com, CN = cyber.local
Getting CA Private Key
bash util/generate_token.sh
         API token is not valid or present
         Generation is required
python src/receipt_server.py
Traceback (most recent call last):
  File "src/receipt_server.py", line 49, in <module>
    config = read_config(util.get_config_dir() + "/config.yml")
  File "/usr/local/lib/python3.6/dist-packages/receipt_parser_core/config.py", line 13, in read_config
    with open(config, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/config/config.yml'
Makefile:10: recipe for target 'serve' failed
make: *** [serve] Error 1
```

Do you have any idea how to fix this problem?

**Comment by monolidth** [comment]
Du nutzt nicht das Docker Image?

**Comment by monolidth** [comment]
But you pull the latest image right?

**Comment by monolidth** [comment]
The launcher script forward the `config.yml` to the Docker Container. Therefore, it required that the `config.yml` is in the root directory.

```
https://raw.githubusercontent.com/ReceiptManager/receipt-parser-server/master/config.yml
```

after, `bash launcher.sh`

**Comment by monolidth** [comment]
Thanks for catching!

Regards,
William

**Comment by monolidth** [comment]
See: https://github.com/ReceiptManager/receipt-parser-server/commit/589c0a997da5210cd4c6398afe6f39958188187e

**Comment by JavaJeremy** [comment]
Thanks, that `config.yml` fixed this problem indeed :)
I still get an error in the app: "Ups something went wrong" but that's a topic for another issue.

**Comment by monolidth** [comment]
Are you using a reverse proxy or the local IP address?

Do you have HTTPS enabled?

Is your server and device  in the same subnet?

**Comment by JavaJeremy** [comment]
See https://github.com/ReceiptManager/receipt-parser-server/issues/31
I'm assuming the connection to the server is working because it was reached.
I'll answer the other questions in that issue.
