### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by 3rsin3rgul-Corplife** [ReceiptManager/receipt-parser-server#57]
Hello,
Are we able to get receipt category or/and expense type?

**Comment by monolidth** [comment]
Good point, receipt categories / expense types are not supported. However, I believe its easy to implement if you map 
market name to category. 

Drawback: you cannot have different expense types for the same market but this would be resolvable by using multiple `config.yml`.

Would this help you?

**Comment by monolidth** [comment]
Sorry, accidently closed
