### ISSUE TITLE
[Docker] Run Recommended instalation finished with failed status

### ISSUE THREAD

**Issue by lukasz18dg** [ReceiptManager/receipt-parser-server#58]
I just tried run docker version mentioned on documentation:
https://receipt-parser-server.readthedocs.io/en/master/installation.html#recommended
`
wget https://raw.githubusercontent.com/ReceiptManager/receipt-parser-server/master/util/launcher.sh
wget https://raw.githubusercontent.com/ReceiptManager/receipt-parser-server/master/config.yml
bash launcher.sh
`
but after run: bash launcher.sh, script finished with error:
`
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
exec /usr/bin/make: exec format error

`
similar for: docker run -i -t monolidth/receipt-parser

**Comment by mochsner** [comment]
Same issue on Ubuntu 20.04 arm64 PC. Should this project be running on a Rasp Pi or something?

**Comment by monolidth** [comment]
Thank you for the report and sorry for the delay. It looks like we both work on different architectures :)

To solve that, you have to build the image from source:
1. Clone project `git clone https://github.com/ReceiptManager/receipt-parser-server && cd receipt-parser-server`
2. Rebuild docker image ` sudo docker build -t monolidth/receipt-parser .  `
3. Copy launcher and execute `cp -r util/launcher.sh . && bash launcher.sh`

Hope this will help you :)
